include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    deprecated_member_use: ignore
    curly_braces_in_flow_control_structures: ignore
    no_leading_underscores_for_local_identifiers: ignore
    constant_identifier_names: ignore
    strict_top_level_inference: ignore
    unnecessary_brace_in_string_interps: ignore
    prefer_final_fields: ignore
    unused_local_variable: ignore
    unused_field: ignore
    unused_element: ignore
    non_constant_identifier_names: ignore
